module.exports = {
    BATTING: [
        "Bat Grip",
        "Stance",
        "Footing",
        "forward defensive",
        "backward defensive",
        "block",
        "Backlift",
        "Vertical-bat strokes",
        "Leave",
        "Leg glance",
        "Off glance",
        "Horizontal-bat shots",
        "flick",
        "Off drive",
        "Square drive",
        "straight drive",
        "On drive ",
        "lofted drive",
        "Depper lofted drive",
        "Cut",
        "Square Cut",
        "Late Cut",
        "Pull Hook",
        "Sweep",
        "paddle sweep",
        "Reverse sweep",
        "Slog sweep",
        "Slog shot",
        "Ramp shot",
        "Upper cut",
        "Switch Hit",
        "Unorthodox strokeplay"
    ],
    BOWLING: [
        "Finger(Off spin left arm orthodox)",
        "Wrist(Leg spin left arm orthodox)",
        "Arm ball",
        "Carrom ball",
        "Doosra",
        "Flipper",
        "Googly",
        "Leg break",
        "Off break ",
        "Slider",
        "Teesra",
        "Topspinner",
        "Bouncer",
        "Inswinger",
        "knuckle ball",
        "Leg cutter",
        "Off cutter",
        "Outswinger",
        "Reverse swing",
        "Slower ball",
        "Yorker",
        "Seam Swing"
    ],
    FIELDING: [
        "Saving one or On the single",
        "Saving two",
        "Right on",
        "Deep long",
        "Short",
        "Silly",
        "Square",
        "Fine",
        "Straight",
        "Wide",
        "Forward",
        "Backward",
        "Slips",
        "side On",
        "Fielding on boundary",
        "cow corner",
        "Austrilan stylye catches",
        "Normal catches",
        "Rapid catches",
        "Cutting the ball",
        "Chasing ball",
    ]

}